#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [41]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [40]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
np.random.randint(0,8,9).reshape(3,3)

array([[2, 4, 3],
       [4, 3, 0],
       [6, 1, 1]])

#### Create a 3x3 identity matrix

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [11]:
np.random.rand(1)

array([0.53457426])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
np.random.random((25))

array([0.26138011, 0.83428434, 0.69772714, 0.19536709, 0.00763193,
       0.11334646, 0.90456154, 0.95779942, 0.32589617, 0.95039746,
       0.91150405, 0.82946469, 0.30388158, 0.38149893, 0.91398539,
       0.10948443, 0.05336263, 0.26453332, 0.30933945, 0.79071703,
       0.42262808, 0.04664475, 0.39546061, 0.20057338, 0.10488692])

#### Create the following matrix:

In [18]:
np.random.uniform(0.0, 1.0, size=(10, 10))

array([[0.56875561, 0.62553276, 0.574162  , 0.9595728 , 0.9800787 ,
        0.15569072, 0.84885244, 0.73844566, 0.00903538, 0.11561913],
       [0.43824323, 0.96318968, 0.09568328, 0.80988222, 0.21436684,
        0.86753525, 0.65850258, 0.54031663, 0.63824398, 0.87976556],
       [0.92093154, 0.05607494, 0.18069966, 0.11552363, 0.54331772,
        0.41253461, 0.46317704, 0.1053619 , 0.15738982, 0.45686953],
       [0.83821329, 0.47756121, 0.04694683, 0.1506674 , 0.3437269 ,
        0.44754138, 0.70849985, 0.01063594, 0.42464294, 0.43804028],
       [0.19517569, 0.12222239, 0.24336862, 0.24458995, 0.96205147,
        0.71065513, 0.35589011, 0.58958565, 0.05175826, 0.05347634],
       [0.51670299, 0.29092588, 0.21259381, 0.9534096 , 0.18133054,
        0.38007261, 0.75069726, 0.48188353, 0.34359749, 0.51365365],
       [0.26323881, 0.30097424, 0.76598535, 0.62853514, 0.23224684,
        0.81520891, 0.96782285, 0.11564612, 0.03763981, 0.7589373 ],
       [0.69245528, 0.34441476, 0.0180539

#### Create an array of 20 linearly spaced points between 0 and 1:

In [23]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [24]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [27]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:4,4:5]

array([[20]])

20

In [28]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[-1:,:]

array([[21, 22, 23, 24, 25]])

array([21, 22, 23, 24, 25])

In [33]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [36]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [37]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [39]:
np.add.reduce(mat,axis=0)

array([55, 60, 65, 70, 75])