### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [76]:
import numpy as np

In [77]:
a=np.random.randint(0,4,25).reshape(5,5)
a

array([[3, 3, 3, 3, 2],
       [3, 1, 3, 0, 0],
       [3, 3, 1, 2, 1],
       [0, 1, 0, 3, 3],
       [0, 0, 1, 1, 3]])

In [78]:
a[0, :], a[-1, :] = a[-1, :].copy(), a[0, :].copy()

In [79]:
a

array([[0, 0, 1, 1, 3],
       [3, 1, 3, 0, 0],
       [3, 3, 1, 2, 1],
       [0, 1, 0, 3, 3],
       [3, 3, 3, 3, 2]])

### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [83]:
arr = np.array([row for row in a if not any(e == 0 for e in row)])
arr


array([[3, 3, 1, 2, 1],
       [3, 3, 3, 3, 2]])

### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [49]:
a=[1.00000000+0.j, 0.70710678+0.70710678j]
np.real(a)

array([1.        , 0.70710678])

In [50]:
np.imag(a)

array([0.        , 0.70710678])

### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [94]:
def Duplicate(arr):
    items=[]
    for i in arr:
        if i not in items:
            items.append(i)
    return items
arr=[10,10,20,20,30,30]
d=Duplicate(arr)
d
            
    
    

            


[10, 20, 30]

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [12]:
a=np.random.randint(0,4,27).reshape(3,3,3)
a

array([[[2, 3, 2],
        [1, 0, 2],
        [2, 3, 3]],

       [[3, 2, 2],
        [2, 2, 0],
        [0, 3, 3]],

       [[3, 0, 1],
        [0, 3, 3],
        [3, 1, 2]]])

### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.
<b>Note:<\b> Do not use builtin sorting function

In [20]:
def Sort(arr,n):
    for i in range(n):
        
        for j in range(n-i-1):
            
            if arr[j]>arr[j+1]:
                temp=arr[j]
                arr[j]=arr[j+1]
                arr[j+1]=temp
    return arr
arr=np.array([3,1,4,2])
n=len(arr)
arr1=Sort(arr,n)
arr1

array([1, 2, 3, 4])

### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [106]:
def checkArrays(arr4, arr5, n, m):
    if n != m:
        return False
    arr4=Sort(arr4,n)
    arr5=Sort(arr5,m)
    for i in range(n):
        if arr4[i] != arr5[i]:
            return False
    return True

arr4 = np.array([2, 1, 2, 4])
arr5 = np.array([2, 1, 3, 4])
n = len(arr4)
m = len(arr5)
checkArrays(arr4, arr5, n, m)

False

### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [64]:
arr3=np.array([[10,40],
               [30,20]])
np.sort(arr3,axis=0)

array([[10, 20],
       [30, 40]])

### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [27]:
a=[-1.6,-1.5,-0.3,0.1,1.4,1.8 ,2. ]
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [29]:
np.ceil(a)


array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [30]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [32]:
start_date = np.datetime64('2017-03-01')
end_date = np.datetime64('2017-03-31')
march_dates = np.arange(start_date,end_date)
march_dates

array(['2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04',
       '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08',
       '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16',
       '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20',
       '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',
       '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28',
       '2017-03-29', '2017-03-30'], dtype='datetime64[D]')

### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [75]:
from datetime import datetime, timedelta
d = datetime(2000, 1, 1, 0, 0)
dates_range = np.array([d + timedelta(hours=i) for i in range(24)])
dates_range

array([datetime.datetime(2000, 1, 1, 0, 0),
       datetime.datetime(2000, 1, 1, 1, 0),
       datetime.datetime(2000, 1, 1, 2, 0),
       datetime.datetime(2000, 1, 1, 3, 0),
       datetime.datetime(2000, 1, 1, 4, 0),
       datetime.datetime(2000, 1, 1, 5, 0),
       datetime.datetime(2000, 1, 1, 6, 0),
       datetime.datetime(2000, 1, 1, 7, 0),
       datetime.datetime(2000, 1, 1, 8, 0),
       datetime.datetime(2000, 1, 1, 9, 0),
       datetime.datetime(2000, 1, 1, 10, 0),
       datetime.datetime(2000, 1, 1, 11, 0),
       datetime.datetime(2000, 1, 1, 12, 0),
       datetime.datetime(2000, 1, 1, 13, 0),
       datetime.datetime(2000, 1, 1, 14, 0),
       datetime.datetime(2000, 1, 1, 15, 0),
       datetime.datetime(2000, 1, 1, 16, 0),
       datetime.datetime(2000, 1, 1, 17, 0),
       datetime.datetime(2000, 1, 1, 18, 0),
       datetime.datetime(2000, 1, 1, 19, 0),
       datetime.datetime(2000, 1, 1, 20, 0),
       datetime.datetime(2000, 1, 1, 21, 0),
       datetime.date

### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example <\b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [110]:
def Concate(s1,s2):
    if len(s1)!=len(s1):
        print("Array is not of same size")
    else:
        arr_s = [a + b for a, b in zip(s1,s2)]
    return arr_s
s1=np.array(['Python','PHP'],dtype='str')
s2=np.array(['java','c++'],dtype='str')
C=Concate(s1,s2)
C


['Pythonjava', 'PHPc++']